image: node:latest

stages:
  - build
  - test

variables:
  CHROME_BIN: /usr/bin/google-chrome # If needed, adjust the path to your Chrome binary

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci # Install dependencies
    - npm run build -- --prod # Build the Angular app for production

test:
  stage: test
  script:
    - npm ci
    - ng test -- --no-watch --browsers=ChromeHeadlessCI # Run tests in headless Chrome